version: '3'

networks:
  talently_net:

services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${SRC_PATH}:/var/www/html:delegated
    depends_on:
      - workspace
      - redis
      - mysql
    networks:
      - talently_net

  mysql:
    image: mysql:5.7.33
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/scripts
    networks:
      - talently_net

  workspace:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}_workspace
    volumes:
      - ${SRC_PATH}:/var/www/html:delegated
    networks:
      - talently_net

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}_redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - talently_net

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ${SRC_PATH}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - talently_net
