version: '3'


services:
  nginx:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-9000}
        - GID=${GID:-9000}
    container_name: ${APP_NAME}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${SRC_PATH}:/var/www/html:delegated
    depends_on:
      - workspace
      - redis
      - mysql

  mysql:
    image: mysql:8.0.28
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/scripts

  workspace:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-9000}
        - GID=${GID:-9000}
    container_name: ${APP_NAME}_workspace
    volumes:
      - ${SRC_PATH}:/var/www/html:delegated

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}_redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379

  npm:
    image: node:17.4.0-alpine3.15
    container_name: ${APP_NAME}_npm
    volumes:
      - ${SRC_PATH}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']